### ISSUE TITLE
Install problem about robot_dart wapper

### ISSUE THREAD

**Issue by emigmo** [resibots/blackdrops#2]
Following the tutorial:
https://github.com/resibots/blackdrops/blob/master/docs/advanced_installation.md
When I install "robot_dart wrapper"
` ./waf configure

Setting top to                           : /home/dex_hand/WorkSpace/robot_dart 

Setting out to                           : /home/dex_hand/WorkSpace/robot_dart/build 

Checking for 'g++' (C++ compiler)        : /usr/bin/g++ 

Checking for 'gcc' (C compiler)          : /usr/bin/gcc 

Checking boost includes                  : 1_54 

Checking boost libs                      : lib regex not found in lib64

(complete log in /home/dex_hand/WorkSpace/robot_dart/build/config.log)
`
All the DART install correctly. for boost libs, I install through "sudo apt-get install libeigen3-dev libassimp-dev libccd-dev libfcl-dev libboost-regex-dev libboost-system-dev"

**Comment by costashatz** [comment]
Hello,

Thanks for using our code.

Which OS are you using? If Ubuntu, can you retry install Boost:

`sudo apt-get install libeigen3-dev libboost-serialization-dev libboost-filesystem-dev libboost-test-dev libboost-program-options-dev libboost-thread-dev libboost-regex-dev`

**Comment by emigmo** [comment]
yes, I use Ubuntu 14.04, the same problem occurs.
When I retry install Boost,
'
libboost-filesystem-dev is already the newest version.
libboost-program-options-dev is already the newest version.
libboost-regex-dev is already the newest version.
libboost-serialization-dev is already the newest version.
libboost-test-dev is already the newest version.
libboost-thread-dev is already the newest version.
libeigen3-dev is already the newest version.

'
By the way,  the "DART"  has been installed correctly.
And the  last few lines of the config.log is following:
'
(tool ar is already loaded, skipping)
/usr/bin/gcc
----------------------------------------
Checking boost includes
1_54
----------------------------------------
Checking boost libs
Found the boost path in /usr/local/lib64 with the libraries:
    /usr/local/lib64/libboost_numpy.so
Trying pattern boost_regex(-gcc[0-9]{0,3})+(-1_54)+
Trying pattern boost_regex(-1_54)+
Trying pattern boost_regex(-1_54)+
Trying pattern boost_regex(-gcc[0-9]{0,3})+
Trying pattern boost_regex
Trying pattern boost_regex
from /home/dex_hand/WorkSpace/robot_dart: lib regex not found in lib64
'

**Comment by costashatz** [comment]
Hey,

I pushed a minor fix in the robot_dart repo. Can you delete the previous folder (of robot_dart), re-clone (from https://github.com/resibots/robot_dart) and re-try?

Let me know if it works or not. Thanks..

**Comment by emigmo** [comment]
The same problem occurs:
bug at:
>     conf.check_boost(lib='regex system filesystem', min_version='1.46')
this is the config.log:

> (tool ar is already loaded, skipping)
/usr/bin/gcc
Checking boost includes
1_54
Checking boost libs
Found the boost path in /usr/local/lib64 with the libraries:
    /usr/local/lib64/libboost_numpy.so
Trying pattern boost_regex(-gcc[0-9]{0,3})+(-1_54)+
Trying pattern boost_regex(-1_54)+
Trying pattern boost_regex(-1_54)+
Trying pattern boost_regex(-gcc[0-9]{0,3})+
Trying pattern boost_regex
Trying pattern boost_regex
from /home/dex_hand/WorkSpace/robot_dart: lib regex not found in lib64

**Comment by costashatz** [comment]
This is weird! The Boost detection that we are using is (almost) the official one and I have already tested it in Ubuntu 14.04. Do you have only one Boost version?

In addition, can you give me the output of `./waf configure` in the limbo folder?

Thanks..

**Comment by emigmo** [comment]
Yesp, only one Boost version in my system.
and the output in the limbo is:

>  ./waf configure
Setting top to                           : /home/dex_hand/WorkSpace/limbo 
Setting out to                           : /home/dex_hand/WorkSpace/limbo/build 
Checking for 'g++' (C++ compiler)        : /usr/bin/g++ 
Checking for 'gcc' (C compiler)          : /usr/bin/gcc 
Checking for compiler flags "-march=native" : yes 
Checking boost includes                     : 1_54 
Checking boost libs                         : lib **serialization** not found in lib64
(complete log in /home/dex_hand/WorkSpace/limbo/build/config.log)

**Comment by emigmo** [comment]
In fact, in my system I type "locate libboost-regex" and "libboost-serialzation" in terminal:

> dex_hand@Dexhand:~/WorkSpace/limbo$ locate libboost-regex
/usr/share/doc/libboost-regex-dev
/usr/share/doc/libboost-regex1.54-dev
/usr/share/doc/libboost-regex1.54.0
/usr/share/doc/libboost-regex-dev/changelog.gz
/usr/share/doc/libboost-regex-dev/copyright
/usr/share/doc/libboost-regex1.54-dev/changelog.Debian.gz
/usr/share/doc/libboost-regex1.54-dev/copyright
/usr/share/doc/libboost-regex1.54.0/changelog.Debian.gz
/usr/share/doc/libboost-regex1.54.0/copyright
/usr/share/lintian/overrides/libboost-regex1.54.0
/var/lib/dpkg/info/libboost-regex-dev:amd64.list
/var/lib/dpkg/info/libboost-regex-dev:amd64.md5sums
/var/lib/dpkg/info/libboost-regex1.54-dev:amd64.list
/var/lib/dpkg/info/libboost-regex1.54-dev:amd64.md5sums
/var/lib/dpkg/info/libboost-regex1.54.0:amd64.list
/var/lib/dpkg/info/libboost-regex1.54.0:amd64.md5sums
/var/lib/dpkg/info/libboost-regex1.54.0:amd64.postinst
/var/lib/dpkg/info/libboost-regex1.54.0:amd64.postrm
/var/lib/dpkg/info/libboost-regex1.54.0:amd64.shlibs
and 

> dex_hand@Dexhand:~/WorkSpace/limbo$ locate libboost-serialization
/usr/share/doc/libboost-serialization-dev
/usr/share/doc/libboost-serialization1.54-dev
/usr/share/doc/libboost-serialization1.54.0
/usr/share/doc/libboost-serialization-dev/changelog.gz
/usr/share/doc/libboost-serialization-dev/copyright
/usr/share/doc/libboost-serialization1.54-dev/changelog.Debian.gz
/usr/share/doc/libboost-serialization1.54-dev/copyright
/usr/share/doc/libboost-serialization1.54.0/changelog.Debian.gz
/usr/share/doc/libboost-serialization1.54.0/copyright
/usr/share/lintian/overrides/libboost-serialization1.54.0
/var/lib/dpkg/info/libboost-serialization-dev:amd64.list
/var/lib/dpkg/info/libboost-serialization-dev:amd64.md5sums
/var/lib/dpkg/info/libboost-serialization1.54-dev:amd64.list
/var/lib/dpkg/info/libboost-serialization1.54-dev:amd64.md5sums
/var/lib/dpkg/info/libboost-serialization1.54.0:amd64.list
/var/lib/dpkg/info/libboost-serialization1.54.0:amd64.md5sums
/var/lib/dpkg/info/libboost-serialization1.54.0:amd64.postinst
/var/lib/dpkg/info/libboost-serialization1.54.0:amd64.postrm
/var/lib/dpkg/info/libboost-serialization1.54.0:amd64.shlibs

The lib are **not**  in `/usr/lib` or `/usr/local` . But I install boost just through `sudo apt-get install libboost-serialization-dev libboost-filesystem-dev libboost-test-dev libboost-program-options-dev libboost-thread-dev libboost-regex-dev` .
Any thing goes wrong?

**Comment by costashatz** [comment]
Can you try running `sudo apt-get install -f`? Because your packages seem
not properly installed..

**Comment by emigmo** [comment]
Can you show me your info about  "locate libboost-regex" and "locate libboost-serialization".
In our other ubuntu systems, it also shows the same info about the localization of the "libboost-regex":

> /usr/share/doc/libboost-regex-dev
/usr/share/doc/libboost-regex-dev/changelog.gz
/usr/share/doc/libboost-regex-dev/copyright
/var/lib/dpkg/info/libboost-regex-dev:amd64.list
/var/lib/dpkg/info/libboost-regex-dev:amd64.md5sums

**Comment by costashatz** [comment]
Most probably you want to try:

``locate libboost_regex``

My output is:

``
/usr/lib/x86_64-linux-gnu/libboost_regex.a

/usr/lib/x86_64-linux-gnu/libboost_regex.so

/usr/lib/x86_64-linux-gnu/libboost_regex.so.1.55.0
``

**Comment by costashatz** [comment]
@emigmo Did you solve your issue?

**Comment by emigmo** [comment]
Yes, After I reinstall my Ubuntu system, All is ok.

**Comment by costashatz** [comment]
> Yes, After I reinstall my Ubuntu system, All is ok.

Great! Let us know if you have any other issue..
