### ISSUE TITLE
Missing release files

### ISSUE THREAD

**Issue by oliverks** [resibots/blackdrops#3]
Some of the repositories are not finding the correct release.  In particular

Err:12 http://ppa.launchpad.net/fcl-debs/ppa/ubuntu bionic Release
  404  Not Found [IP: 91.189.95.83 80]
Err:14 http://ppa.launchpad.net/libccd-debs/ppa/ubuntu bionic Release
  404  Not Found [IP: 91.189.95.83 80]

I modified the 

dartsim-ubuntu-ppa-bionic.list    
libccd-debs-ubuntu-ppa-bionic.list
fcl-debs-ubuntu-ppa-bionic.list

to include the devel branch as the bionic branches do not exist.

I think this might be a problem with the way the repos are adding the install scripts.

**Comment by costashatz** [comment]
This is because some PPAs do not exist in the latest versions of Ubuntu (see [DART docs](http://dartsim.github.io/install_dart_on_ubuntu.html#install-dart-using-ubuntu-packages)); I will fix this in the scripts. Thanks for catching this.

**Comment by costashatz** [comment]
This should be fixed with #5. @oliverks please let me know if it persists.. Thanks..
